version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "darkstarlabs-accounts"
    grouping:
      update-types:
        - "major"
        - "minor"
        - "patch"
